# Generated by Django 4.0.5 on 2022-06-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('description', models.TextField()),
                ('cover_image_key', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
