# Generated by Django 4.0.5 on 2022-07-02 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('primary_image_key', models.CharField(max_length=256, unique=True)),
                ('secondary_image_key', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='uuid',
        ),
        migrations.AddField(
            model_name='album',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Personage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('artifacts', models.ManyToManyField(to='restapp.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('Artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.artifact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.album'),
        ),
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('page_image_key', models.CharField(max_length=256, unique=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.album')),
            ],
        ),
    ]
