name: django-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10.5']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install awscli
    - name: Run Docker Compose
      run: docker-compose -f "docker-compose-dev.yaml" up -d
    - name: Create LocalStack Bucket
      run: |
        aws --no-sign-request --endpoint-url=http://localhost:4566 s3 mb s3://dolunay-storage
    - name: Configure AWS
      run: aws configure set aws_access_key_id "test" --profile localstack && aws configure set aws_secret_access_key "test" --profile localstack && aws configure set output "json" --profile localstack
    - name: Run Tests
      working-directory: ./api
      run: |
        python manage.py test

#    services:
#      postgres_main:
#        image: postgres:latest
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: github_actions
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#      localstack:
#        image: localstack/localstack
#        ports:
#          - 4566:4566

